# [package] is not actually used currently, it's just here for some reason
[package]
name = "simple"
version = "0.1.0"
authors = ["foo"]
description = "bar"

[build]
build_sys = "cmake"
build_sys_ver = "3.15"
build_dir = "build/"
edition = "c11"
compiler = "clang"

[[unit]]
name = "simple"
kind = "bin"
src = ["src/"]
